name: Update Players JSON

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:       
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm install firebase-admin

      - name: Run update script
        run: node scripts/updatePlayers.js
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add players.json
          git commit -m "Update players.json"
          git push
